name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Rust using rustup
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable # You can specify nightly if needed
          profile: minimal
          override: true

      # Install Node.js (required for Tauri)
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Tauri recommends Node.js 16+ for compatibility

      # Install Yarn
      - name: Install Yarn
        run: npm install -g yarn

      # Install frontend dependencies with Yarn
      - name: Install dependencies with Yarn
        run: yarn install

      # Install CMake (if needed, or upgrade to a specific version)
      - name: Install CMake
        run: |
          brew install cmake  # Install or update CMake using Homebrew

      # Build the Tauri application
      - name: Build Tauri App
        run: |
          yarn tauri build --bundles dmg
