name: CI Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      # Install Rust using rustup
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      # Install Node.js (required for Tauri)
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Tauri recommends Node.js 16+ for compatibility

      # Install Yarn
      - name: Install Yarn
        run: npm install -g yarn

      # Install frontend dependencies with Yarn
      - name: Install dependencies with Yarn
        run: yarn install

      # Build the Tauri application
      - name: Build Tauri App
        run: |
          yarn tauri build --bundles dmg

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          body: "Release of MediaTool.app v1.0.1."
          files: |
            src-tauri/target/release/bundle/dmg/*.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}